# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\scheduler_sim_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(900, 600)
        main_window.setMinimumSize(QtCore.QSize(900, 600))
        main_window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        main_window.setMouseTracking(False)
        main_window.setAutoFillBackground(False)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setEnabled(True)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.title_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.title_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_label.setScaledContents(True)
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setWordWrap(False)
        self.title_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title_label.setObjectName("title_label")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(780, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_start.setObjectName("pushButton_start")
        self.terminal_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.terminal_output.setGeometry(QtCore.QRect(10, 410, 881, 141))
        self.terminal_output.setObjectName("terminal_output")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(670, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(10, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_help.setObjectName("pushButton_help")
        self.groupBox_add = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_add.setGeometry(QtCore.QRect(10, 60, 861, 61))
        self.groupBox_add.setAutoFillBackground(True)
        self.groupBox_add.setObjectName("groupBox_add")
        self.label = QtWidgets.QLabel(self.groupBox_add)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spin_arraival_time = QtWidgets.QSpinBox(self.groupBox_add)
        self.spin_arraival_time.setGeometry(QtCore.QRect(430, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spin_arraival_time.setFont(font)
        self.spin_arraival_time.setObjectName("spin_arraival_time")
        self.label_arrival_time = QtWidgets.QLabel(self.groupBox_add)
        self.label_arrival_time.setGeometry(QtCore.QRect(300, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_arrival_time.setFont(font)
        self.label_arrival_time.setObjectName("label_arrival_time")
        self.label_burst_time = QtWidgets.QLabel(self.groupBox_add)
        self.label_burst_time.setGeometry(QtCore.QRect(560, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_burst_time.setFont(font)
        self.label_burst_time.setObjectName("label_burst_time")
        self.spin_burst_time = QtWidgets.QSpinBox(self.groupBox_add)
        self.spin_burst_time.setGeometry(QtCore.QRect(680, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spin_burst_time.setFont(font)
        self.spin_burst_time.setObjectName("spin_burst_time")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(780, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_add.setObjectName("pushButton_add")
        self.groupBox_choose = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_choose.setGeometry(QtCore.QRect(10, 160, 861, 191))
        self.groupBox_choose.setAutoFillBackground(True)
        self.groupBox_choose.setObjectName("groupBox_choose")
        self.label_choose_scheduler = QtWidgets.QLabel(self.groupBox_choose)
        self.label_choose_scheduler.setGeometry(QtCore.QRect(10, 20, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_choose_scheduler.setFont(font)
        self.label_choose_scheduler.setObjectName("label_choose_scheduler")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_choose)
        self.radioButton.setGeometry(QtCore.QRect(30, 70, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_choose)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 110, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptionen = QtWidgets.QMenu(self.menubar)
        self.menuOptionen.setObjectName("menuOptionen")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionTest = QtWidgets.QAction(main_window)
        self.actionTest.setObjectName("actionTest")
        self.actionBeenden = QtWidgets.QAction(main_window)
        self.actionBeenden.setObjectName("actionBeenden")
        self.menuOptionen.addAction(self.actionTest)
        self.menuOptionen.addSeparator()
        self.menuOptionen.addAction(self.actionBeenden)
        self.menubar.addAction(self.menuOptionen.menuAction())
        self.label_arrival_time.setBuddy(self.spin_arraival_time)
        self.label_burst_time.setBuddy(self.spin_burst_time)
        self.label_choose_scheduler.setBuddy(self.radioButton)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.spin_arraival_time, self.spin_burst_time)
        main_window.setTabOrder(self.spin_burst_time, self.pushButton_add)
        main_window.setTabOrder(self.pushButton_add, self.radioButton)
        main_window.setTabOrder(self.radioButton, self.radioButton_2)
        main_window.setTabOrder(self.radioButton_2, self.pushButton_help)
        main_window.setTabOrder(self.pushButton_help, self.pushButton_cancel)
        main_window.setTabOrder(self.pushButton_cancel, self.pushButton_start)
        main_window.setTabOrder(self.pushButton_start, self.terminal_output)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Scheduler Simluator by Alexander Müller"))
        self.title_label.setText(_translate("main_window", "Scheduling Simluator"))
        self.pushButton_start.setText(_translate("main_window", "Start"))
        self.pushButton_cancel.setText(_translate("main_window", "Cancel"))
        self.pushButton_help.setText(_translate("main_window", "Help"))
        self.groupBox_add.setTitle(_translate("main_window", "GroupBox"))
        self.label.setText(_translate("main_window", "Add a Process"))
        self.label_arrival_time.setText(_translate("main_window", "Arrival Time:"))
        self.label_burst_time.setText(_translate("main_window", "Burst Time:"))
        self.pushButton_add.setText(_translate("main_window", "Add"))
        self.groupBox_choose.setTitle(_translate("main_window", "GroupBox"))
        self.label_choose_scheduler.setText(_translate("main_window", "Choose a Scheduler"))
        self.radioButton.setText(_translate("main_window", "First Come - First Serve"))
        self.radioButton_2.setText(_translate("main_window", "Smallest Job First"))
        self.menuOptionen.setTitle(_translate("main_window", "Optionen"))
        self.actionTest.setText(_translate("main_window", "Test"))
        self.actionBeenden.setText(_translate("main_window", "Beenden"))
